### ISSUE TITLE
Make tab title in center

### ISSUE THREAD

**Issue by Im-Kal** [Dook97/firefox-config#1]
![image](https://user-images.githubusercontent.com/69103102/169648132-a35d0d2e-39b8-4bce-b6db-56bc42e8eeeb.png)

As show in the screenshot, is it possible to make the text in the center of the tab?

**Comment by Dook97** [comment]
Try adding [this](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/centered_tab_content.css) to your `userChrome.css`. I tried it out quickly and it seemed to work.

**Comment by Im-Kal** [comment]
Thanks a lot, also do you have any idea on how would I center the text **vertically**?
![image](https://user-images.githubusercontent.com/69103102/169656249-a3c19bd1-7c4d-49c0-b4be-6286135f4555.png)
Like it is stuck to the bottom of the tab, I would like to make it to the center of the tab vertically.

![image](https://user-images.githubusercontent.com/69103102/169656472-f2bb51b7-673e-4560-9fab-a96a60477543.png)
Like this.

**Comment by Im-Kal** [comment]
Also how do I remove the black bar (highlighted by red)?
![image](https://user-images.githubusercontent.com/69103102/169656504-818ed9d2-372a-492b-aae5-1c6709325f1b.png)

Sorry if I am asking a lot, I used to do CSS but forgot everything.

**Comment by Dook97** [comment]
I've been fighting with vertical centering for some time. Haven't been able to do it yet :p

> black bar

Did you enable compact mode as it says in the readme?

**Comment by Im-Kal** [comment]
I did.
Lemme recheck
Also how the hell you replied so fast lol

**Comment by Im-Kal** [comment]
![image](https://user-images.githubusercontent.com/69103102/169656751-ce75bf9c-f1e2-4d06-88e9-6808ce34d8b9.png)

**Comment by Dook97** [comment]
I'm sorry - I only ever tested on my machine, so you get to be the labrat apparently :D

Maybe try disabling the Touch for Tablet Mode thing - don't know what that is and it doesn't even show for me.

What resolution is your monitor? Does it change for the better if you set it to 1920x1080?

>  Also how the hell you replied so fast lol

I'm writing a program for a class in uni, so I'm on github constantly :)

**Comment by Im-Kal** [comment]
lol, lemme try again

Update : Doesn't work


It works if I change the resolution of firefox window, is there any permanent fix?

**Comment by Dook97** [comment]
> It works if I change the resolution of firefox window

What do you mean exactly? Doesn't work in fullscreen but works when windowed?

> is there any permanent fix?

A sort of "fix" might be increasing the `--tab-min-height` value.

**Comment by Im-Kal** [comment]
So basically if I snap the Firefox window to any edge, the black bar becomes extended but when I change firefox to cover my entire screen the black bar is reduced. I saw ```stack``` which had ```position : relative;``` could that be causing the issue?

**Comment by Im-Kal** [comment]
Firefox covering my entire screen:
![image](https://user-images.githubusercontent.com/69103102/169657449-1ca96c1f-e46e-477f-9262-eebc5e873897.png)

Small portion of my screen:
![image](https://user-images.githubusercontent.com/69103102/169657467-f42bf155-0ac0-4fc9-becd-8e6776579b28.png)

**Comment by Im-Kal** [comment]
When I change ```--tab-min-height```

![image](https://user-images.githubusercontent.com/69103102/169657509-a328cc72-f6fc-40be-bf73-11b824971b66.png)

**Comment by Dook97** [comment]
That's really weird. Two things come to mind and after that I just don't know.

1) Try removing the create new tab button on the top right (through the customize toolbar menu).
2) Try removing the urlbar autohiding portion of the code on the bottom of the file.

**Comment by Im-Kal** [comment]
Alright sure, lemme try.

**Comment by Im-Kal** [comment]
Doing all of these did not help, though on pages where the URL is not present (Customize Toolbar) the space remained even. So I think it's the URL code or the width stuff.

**Comment by Im-Kal** [comment]
Is there anything I can do? I wanted to use Qutebrowser as I anyways use Vimuim. But due to Qutebrowser being based on non-standard backend, I cannot use my extensions like UBlock. I wanted to use Firefox/LibreWolf with this config and it would be really nice as this is the only maintained theme resembling Qutebrowser

**Comment by Dook97** [comment]
I think I realised why the `--tab-min-height` "fix" didn't work. I had the value of the variable hardcoded elsewhere so it didn't fully propagate when you changed it. I pushed a fix. Would you try increasing it now?

**Comment by Im-Kal** [comment]
Sure lemme try

**Comment by Im-Kal** [comment]
How can I obtain the fix? the last commit was 15 hours ago.

**Comment by Dook97** [comment]
That's just my schizo git config lying about commit times :) - the fix was actually pushed a few minutes ago.

**Comment by Im-Kal** [comment]
Okay lemme check again.

**Comment by Im-Kal** [comment]
It's working! Thanks a lot :D

**Comment by Dook97** [comment]
Great! :)
Plase do let me know if there are any other issues.

**Comment by Im-Kal** [comment]
Sure, thank you!

**Comment by Im-Kal** [comment]
Also a small issue when I imported it to LibreWolf, the bookmarks icon is hidden but the hitbox still triggers. How do I fix that?

**Comment by Dook97** [comment]
That's actually intentional eventhough it's ugly. It's because if the hitbox is removed you can't use Ctrl+D. If it bothers you you have two options:

~~remove this line: `#star-button { display: none; }` to make the star button visible~~ nope, that will break stuff

or add this line `#star-button-box { display: none; }` to remove the hitbox

**Comment by Im-Kal** [comment]
Also the suggestions do not show up, what should I do please?

**Comment by Dook97** [comment]
That shouldn't be related to the userChrome.css I think. Look into your settings. Do you have search suggestions enabled? Also look into `about:config` specificaly the `browser.urlbar.maxRichResults` variable. If you have a `-1` there that's why suggestions aren't showing.

**Comment by Im-Kal** [comment]
Hello! sorry for the late reply, I had some work. After applying the fix, the text in the tab is now vertically aligned and also I did not need to enable the suggestion box as Teradactly's ```,T``` was more than enough. Thanks a lot for the support and the awesome userChrome.css
