### ISSUE TITLE
urlbar unselected foreground  color

### ISSUE THREAD

**Issue by ghost** [Dook97/firefox-config#10]
it's simply too dark, on a dark background too
![image](https://github.com/Dook97/firefox-qutebrowser-userchrome/assets/60894565/c0d11d44-7818-4be2-bf1e-fd4f77ce77e3)

is there any way to make the font white, like it is in private mode?

P.S.: i don't want to enable dark mode

**Comment by Dook97** [comment]
```css
#urlbar {
	color: #fff !important;
}
```

But this userchrome really doesn't work well without dark theme. You'll have to
change a bunch of other things or have a sub-optimal experience.

**Comment by ghost** [comment]
Another question: how do I do the same for the search bar?

**Comment by Dook97** [comment]
I'm currently very busy, so I won't look it up for you, but you can figure it out yourself. See [here](https://old.reddit.com/r/FirefoxCSS/comments/73dvty/tutorial_how_to_create_and_livedebug_userchromecss/) for a how-to.
