### ISSUE TITLE
tab titles and favicons are not centered vertically in latest nightly

### ISSUE THREAD

**Issue by ghost** [Dook97/firefox-config#15]
this is how they look now (i use a different font though)

![image](https://github.com/user-attachments/assets/7864963f-0a15-4974-9825-1865d42e0a52)

**Comment by Dook97** [comment]
Thanks for reporting. I'll fix when I can reproduce the issue in latest release. In the meantime, as a temporary measure, try increasing the value of the `--tab-min-height` variable.

**Comment by ghost** [comment]
i set it to 20 (instead of 16) and it still has the same issue - it's aligned towards the bottom. i guess i'll switch to firefox release

**Comment by Dook97** [comment]
Sorry I can't help you more, but I don't have the capacity to fiddle with nightly right now.

You can try troubleshooting yourself. [Here's](https://www.youtube.com/watch?v=d2hRQu6rkDg) a guide I made. There are others if you don't like mine.
