### ISSUE TITLE
not working on firefox 133

### ISSUE THREAD

**Issue by Monirzadeh** [Dook97/firefox-config#16]
Hi
thanks for userchrome. after update firefox 133.0 userchrome break.
![1](https://github.com/user-attachments/assets/126ca0bd-a02e-4be8-bc8b-70298b12b6a8)

**Comment by Dook97** [comment]
Hi, I've pushed an emergency fix. I hope to fully restore the original look in a few days at most.

**Comment by Monirzadeh** [comment]
Thanks.
i test last PR things get better. hide urlbar not working yet.

**Comment by Dook97** [comment]
Ugly solution. If anyone comes up with a better one I'll be happy to accept a PR.
