### ISSUE TITLE
showing the URL when hovering on hyperlink

### ISSUE THREAD

**Issue by khlsvr** [Dook97/firefox-config#18]
As a long time qutebrowser user I like this userChrome.css. I only made few changes to it and it's usable. I want to see the URL all the time, so I enabled the urlbar. Also I want the back button accessible with mouse in right click menu so I put that back. 

Anyway there's one nuisance and that's when I hover mouse over a hyperlink, I can't tell where the link points to. On qutebrowser the "urlbar" swaps to show where the link takes you when you hover mouse over a hyperlink. I guess that's impossible on firefox, but I would be happy to have the original firefox behavior back, where the URL of the hovered hyperlink is shown in the bottom left of the screen. I see on your userChrome.css you are doing things on navbar, urlbar and toolbar but I'm not sure if any of those matches the bottom left area showing the URL. If it's possible to put it back, I would also like to change the fontsize of that url text.  Anyone?

**Comment by Dook97** [comment]
remove [this](https://github.com/Dook97/firefox-qutebrowser-userchrome/blob/4b8963c44eae7abc20e6aacb5c571aeeb4432ead/userChrome.css#L30)

To change the font

```css
#statuspanel {
    font-family: yourfont !important;
}
```

should do the trick.
