### ISSUE TITLE
Blue color only  in tabs

### ISSUE THREAD

**Issue by cammpion** [Dook97/firefox-config#3]
I just modify the font and its size. But still just using the original file, it is always showing the blue tabs.

I use windows

image - https://cdn.discordapp.com/attachments/859975589430296606/1004071828358189186/Untitled.png

**Comment by Dook97** [comment]
Are you using containers? The color of the text inside the tab is determined by the container color. If a container isn't used it will default to white text.

**Comment by Dook97** [comment]
Also I see that you have encountered the black stripe bug. You can fix that by increasing `--tab-min-height` on line 107. 20px should work.

**Comment by cammpion** [comment]
all fixed now! thank you!
