### ISSUE TITLE
Dark space between pinned tab and first not pinned tab

### ISSUE THREAD

**Issue by dibusure** [Dook97/firefox-config#4]
Hello, i just installed qutebrowser userchrome. I really like it, but i always have one pinned tab for music ( yandex.music )
![image](https://user-images.githubusercontent.com/69085213/185083730-67640d05-cf31-44f8-a8af-acf0d18aa526.png)
It usually works fine ( with other userchromes ), but here...

**Comment by dibusure** [comment]
it will be better this way
![image](https://user-images.githubusercontent.com/69085213/185084150-e1fe1049-ac18-4bc9-b832-1395805002ee.png)

**Comment by Dook97** [comment]
Thanks for reporting. The issue should be fixed now; see c827372

Pinned tabs look pretty bad without favicons though - just empty squares. Might've to do something about that...
