### ISSUE TITLE
Pinned favicon not full (idk) + screenshot

### ISSUE THREAD

**Issue by dibusure** [Dook97/firefox-config#5]
![image](https://user-images.githubusercontent.com/69085213/185236374-cb7be352-a9f7-46ba-9b13-85de3cd1c848.png)

this happens when I open so many tabs that the arrow on the right appears (idk)

**Comment by dibusure** [comment]
maybe it's not possible, but u can replace favicon of pinned website with first uppercase letter of domain. ex: for `music.yandex.ru` -- Y, `google.com` -- G. it will be cool

**Comment by Dook97** [comment]
Thanks for reporting. Should be fixed now; see c285fba

> Can you replace favicon with first letter of domain?

I'm happy with how favicons look in pinned tabs, so I won't try to implement this myself. If you figure it out, feel free to make a PR and I might consider it as an option which the user can uncomment.
