### ISSUE TITLE
Hide tab status or move it next to the tab title

### ISSUE THREAD

**Issue by enzom-uy** [Dook97/firefox-config#7]
Hi! Thank you for this theme, it's amazing.

I'd like to know if there's a way to hide the tab status (Playing, Muted/Unmuted, etc), or move it next to the title.

![image](https://user-images.githubusercontent.com/94983952/209722680-521287a1-7da7-4920-8a51-b8793540fe2d.png)

**Comment by Dook97** [comment]
Weird, doesn't happen for me eventhough my locale is set to US.

Well, you can try [this](https://support.mozilla.org/en-US/questions/13668070) as a temporary hack until I get around to implementing a proper solution.

**Comment by enzom-uy** [comment]
The link is broken but I found a workaround, maybe it's the same solution that you linked:

> You could change the density to Compact mode. That will hide the Playing text but leave the speaker icon.
>
>about:config change browser.compactmode.show to true, then select Customize toolbar and change the density option >to Compact

[Source](https://www.reddit.com/r/firefox/comments/nym34x/is_there_a_way_to_disablemodify_the_playing_text/)

I'm gonna close the issue, ty!

**Comment by Dook97** [comment]
I can't refrain from pointing out that users are instructed to enable compact mode in the README ;p

The (broken) link I sent was some sort of hack with locales - not that it matters.
