### ISSUE TITLE
When the tab reaches a certain number, the tab bar keeps flashing

### ISSUE THREAD

**Issue by lost22git** [Dook97/firefox-config#9]
![cc](https://github.com/Dook97/firefox-qutebrowser-userchrome/assets/65008815/b8ece9bd-6241-443e-82a1-12118f77a3c5)

**Comment by Dook97** [comment]
Weird. Please try reproducing this with a new clean profile and without any modifications to my userchrome. Could be something else in your config not playing well with it.

It doesn't happen for me even if I open an extreme number of tabs.

**Comment by lost22git** [comment]
Hi @Dook97 , it can be reproduced in the scene where there are multiple pin tabs at the same time

![cc](https://github.com/Dook97/firefox-qutebrowser-userchrome/assets/65008815/51188a83-dd71-4b22-b215-7084568fa673)

**Comment by Dook97** [comment]
Yes, now I was able to reproduce it as well.

Honestly I have no idea what's happening and since I don't use pinned tabs I'm
not really motivated to try and fix it. If you (or anyone else for that matter)
manages to fix this, create a PR and I'll merge it.
